"""create periodes table

Revision ID: 8f0138aedd63
Revises: 646f79c52a86
Create Date: 2025-11-01 21:43:32.161407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0138aedd63'
down_revision: Union[str, Sequence[str], None] = '646f79c52a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_name')
    )
    op.create_index(op.f('ix_periodes_id'), 'periodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodes_id'), table_name='periodes')
    op.drop_table('periodes')
    # ### end Alembic commands ###
